version: '3.8'

services:
  cargo-db:
    image: postgres:15-alpine
    container_name: cargo_tracking_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "050305"
      POSTGRES_DB: CargoTrackingDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cargo-api:
    image: cargo-tracking-api
    container_name: cargo_tracking_webapi
    build:
      context: .
      dockerfile: CargoTrackingSystem.WebAPI/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=cargo-db;Database=CargoTrackingDb;Username=postgres;Password=050305
    depends_on:
      - cargo-db

volumes:
  postgres_data: